AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for lucid-web-api

Parameters:
  ApiDomainName:
    Description: The Domain that the Api Will be accessible from
    Type: String
  ApiCertArn: 
    Description: Certificate arn for the api gateway
    Type: String
  HostedZoneId:
    Description: The Hosted Zone Id for the Domain
    Type: String

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Lucid-Web-Api-Gateway
      Description: The entry-point to the Lucid Web App Api
      StageName: Dev
      Domain:
        DomainName: !Ref ApiDomainName
        CertificateArn: !Ref ApiCertArn
        Route53:
          HostedZoneId: !Ref HostedZoneId

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /hello
            Method: get

